import Head from "next/head";
import Main from "../src/components/Main/Main";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css"
          media="screen"
        />

        <script src="../src/lib/js/jquery.min.js" />
        <script src="../src/lib/js/popper.min.js" />
        <script src="../src/lib/js/bootstrap.bundle.min.js" />
        <script src="../src/lib/js/jquery-3.0.0.min.js" />
        <script src="../src/lib/js/plugin.js" />
        <script src="../src/lib/js/jquery.mCustomScrollbar.concat.min.js" />
        <script src="../src/lib/js/custom.js" />
        <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js" />
      </Head>

      <main>
        <Main />
      </main>
    </div>
  );
}
